package rules

import (
	"regexp"
	"strings"

	"github.com/messagesgoel-blip/slopgate/pkg/diff"
)

// SLP031 flags documentation files that indicate direct code intake
// from external sources without proper license validation.
//
// Pattern: Files mentioning "direct-code intake", "upstream repo", 
// "Lovable-generated", or similar patterns that suggest external code
// without explicit license review.
//
// Rationale: External code intake without proper license validation
// can introduce legal risks. Files should have proper attribution
// and license compatibility verification.
type SLP031 struct{}

func (SLP031) ID() string                { return "SLP031" }
func (SLP031) DefaultSeverity() Severity { return SeverityWarn }
func (SLP031) Description() string {
	return "documentation indicates external code intake without license validation"
}

// slp031IntakePatterns matches patterns indicating external code intake.
var slp031IntakePatterns = []*regexp.Regexp{
	regexp.MustCompile(`(?i)(direct.code|intake|upstream repo|Lovable.generated|third.party|external source)`),
	regexp.MustCompile(`(?i)(borrowed from|copied from|adapted from|ported from)`),
	regexp.MustCompile(`(?i)(scaffold only|generated by|created by|template from)`),
}

// slp031LicensePatterns matches patterns indicating license validation.
var slp031LicensePatterns = []*regexp.Regexp{
	regexp.MustCompile(`(?i)(license check|license validated|oss approved|legal reviewed)`),
	regexp.MustCompile(`(?i)(license compatibility|license review completed)`),
}

func (r SLP031) Check(d *diff.Diff) []Finding {
	var out []Finding
	for _, f := range d.Files {
		if f.IsDelete {
			continue
		}
		
		// Only check documentation files
		lowerPath := strings.ToLower(f.Path)
		if !strings.Contains(lowerPath, "readme") && 
		   !strings.Contains(lowerPath, "attribution") && 
		   !strings.Contains(lowerPath, "notice") &&
		   !strings.Contains(lowerPath, "license") &&
		   !strings.Contains(lowerPath, "doc") &&
		   !strings.HasSuffix(lowerPath, ".md") {
			continue
		}

		for _, h := range f.Hunks {
			var contentLines []string
			for _, ln := range h.Lines {
				if ln.Kind == diff.LineAdd {
					contentLines = append(contentLines, ln.Content)
				}
			}
			
			content := strings.Join(contentLines, "\n")
			
			// Check if it contains intake patterns
			hasIntakePattern := false
			for _, pattern := range slp031IntakePatterns {
				if pattern.MatchString(content) {
					hasIntakePattern = true
					break
				}
			}
			
			if !hasIntakePattern {
				continue
			}
			
			// Check if it contains license validation patterns
			hasLicenseValidation := false
			for _, pattern := range slp031LicensePatterns {
				if pattern.MatchString(content) {
					hasLicenseValidation = true
					break
				}
			}
			
			if !hasLicenseValidation {
				// Find the first line with an intake pattern to report
				for _, ln := range h.Lines {
					if ln.Kind == diff.LineAdd {
						for _, pattern := range slp031IntakePatterns {
							if pattern.MatchString(ln.Content) {
								out = append(out, Finding{
									RuleID:   r.ID(),
									Severity: r.DefaultSeverity(),
									File:     f.Path,
									Line:     ln.NewLineNo,
									Message:  "external code intake detected without license validation confirmation",
									Snippet:  strings.TrimSpace(ln.Content),
								})
								break
							}
						}
						if len(out) > 0 && out[len(out)-1].File == f.Path {
							break // Only report once per file
						}
					}
				}
			}
		}
	}
	return out
}