package rules

import (
	"regexp"
	"strings"

	"github.com/messagesgoel-blip/slopgate/pkg/diff"
)

// SLP100 flags functions that return a zero value with no side effects.
// These are stubs that were likely generated by an AI agent and left
// unfinished.
type SLP100 struct{}

func (SLP100) ID() string                { return "SLP100" }
func (SLP100) DefaultSeverity() Severity { return SeverityBlock }
func (SLP100) Description() string {
	return "function returns zero value with no side effects — likely an unfinished stub"
}

var slp100FuncStart = regexp.MustCompile(`(?i)(?:func\s+|function\s+|def\s+|public\s+(?:static\s+)?(?:void\s+)?|private\s+(?:static\s+)?|fn\s+)\w+\s*\(`)

var slp100ZeroReturn = regexp.MustCompile(`(?i)^\s*return\s+(nil|null|0|false|""|''|\[\]|\{\}|undefined|None|nil\))\s*[;]?\s*$`)

func hasSideEffect(line string) bool {
	stripped := stripCommentAndStrings(line)
	if strings.HasPrefix(strings.TrimSpace(stripped), "return") {
		return false
	}
	stripped = strings.TrimSpace(stripped)
	if stripped == "" || stripped == "{" || stripped == "}" {
		return false
	}
	return true
}

func (r SLP100) Check(d *diff.Diff) []Finding {
	var out []Finding
	for _, f := range d.Files {
		if f.IsDelete || isDocFile(f.Path) {
			continue
		}
		if !isGoFile(f.Path) && !isJSOrTSFile(f.Path) && !isPythonFile(f.Path) && !isJavaFile(f.Path) && !isRustFile(f.Path) {
			continue
		}

		for _, h := range f.Hunks {
			inFunc := false
			braceDepth := 0
			hasWork := false
			firstLine := true

			for _, ln := range h.Lines {
				if ln.Kind != diff.LineAdd {
					continue
				}
				content := strings.TrimSpace(ln.Content)

				if !inFunc && slp100FuncStart.MatchString(content) {
					inFunc = true
					braceDepth = 0
					hasWork = false
					firstLine = true
				}

				if inFunc {
					braceDepth += strings.Count(content, "{")
					braceDepth -= strings.Count(content, "}")

					if !firstLine && hasSideEffect(content) && !slp100ZeroReturn.MatchString(content) {
						hasWork = true
					}
					firstLine = false

					if braceDepth <= 0 && strings.Contains(content, "}") {
						if !hasWork {
							for _, pln := range h.Lines {
								if pln.Kind == diff.LineAdd && slp100FuncStart.MatchString(strings.TrimSpace(pln.Content)) {
									out = append(out, Finding{
										RuleID:   r.ID(),
										Severity: r.DefaultSeverity(),
										File:     f.Path,
										Line:     pln.NewLineNo,
										Message:  "function appears to be a no-op stub — implement the body or add a TODO if intentional",
										Snippet:  strings.TrimSpace(pln.Content),
									})
									break
								}
							}
						}
						inFunc = false
					}
				}
			}
		}
	}
	return out
}
