package rules

import (
	"regexp"
	"strings"

	"github.com/messagesgoel-blip/slopgate/pkg/diff"
)

// SLP100 flags functions that return a zero value with no side effects.
// These are stubs that were likely generated by an AI agent and left
// unfinished.
type SLP100 struct{}

func (SLP100) ID() string                { return "SLP100" }
func (SLP100) DefaultSeverity() Severity { return SeverityBlock }
func (SLP100) Description() string {
	return "function returns zero value with no side effects — likely an unfinished stub"
}

var slp100FuncStart = regexp.MustCompile(`(?i)(?:func\s+(?:\([^)]*\)\s+)?|function\s+|def\s+|(?:public|private|protected)\s+(?:static\s+)?(?:final\s+)?(?:\w+\s+)?|fn\s+)\w+\s*\(`)

var slp100ZeroReturn = regexp.MustCompile(`(?i)^\s*return(?:\s+(nil|null|0|false|""|''|\[\]|\{\}|undefined|None))?\s*[;]?\s*$`)

func hasSideEffect(line string) bool {
	stripped := stripCommentAndStrings(line)
	trimmed := strings.TrimSpace(stripped)
	if strings.HasPrefix(trimmed, "return") {
		return !slp100ZeroReturn.MatchString(trimmed)
	}
	if trimmed == "" || trimmed == "{" || trimmed == "}" {
		return false
	}
	return true
}

func (r SLP100) Check(d *diff.Diff) []Finding {
	var out []Finding
	for _, f := range d.Files {
		if f.IsDelete || isDocFile(f.Path) {
			continue
		}
		if !isGoFile(f.Path) && !isJSOrTSFile(f.Path) && !isJavaFile(f.Path) && !isRustFile(f.Path) {
			continue
		}

		for _, h := range f.Hunks {
			inFunc := false
			braceDepth := 0
			hasWork := false
			firstLine := true
			var funcLineNo int
			var funcSnippet string

			for _, ln := range h.Lines {
				if ln.Kind != diff.LineAdd {
					inFunc = false
					continue
				}
				content := strings.TrimSpace(ln.Content)

				if !inFunc && slp100FuncStart.MatchString(stripCommentAndStrings(content)) {
					inFunc = true
					braceDepth = 0
					hasWork = false
					firstLine = true
					funcLineNo = ln.NewLineNo
					funcSnippet = content
					// Check the body fragment on the same line (text after the opening '{').
					if idx := strings.Index(content, "{"); idx >= 0 {
						bodyFragment := strings.TrimSpace(content[idx+1:])
						// Remove at most one trailing '}' so "return {} }" becomes "return {}" not "return {".
						if strings.HasSuffix(bodyFragment, "}") {
							bodyFragment = bodyFragment[:len(bodyFragment)-1]
						}
						if hasSideEffect(bodyFragment) {
							hasWork = true
						}
					}
				}

				if inFunc {
					cleanContent := stripCommentAndStrings(content)
					braceDepth += strings.Count(cleanContent, "{")
					braceDepth -= strings.Count(cleanContent, "}")

					if !firstLine && hasSideEffect(content) {
						hasWork = true
					}
					firstLine = false

					if braceDepth <= 0 && strings.Contains(cleanContent, "}") {
						if !hasWork {
							out = append(out, Finding{
								RuleID:   r.ID(),
								Severity: r.DefaultSeverity(),
								File:     f.Path,
								Line:     funcLineNo,
								Message:  "function appears to be a no-op stub — implement the body or add a TODO if intentional",
								Snippet:  funcSnippet,
							})
						}
						inFunc = false
					}
				}
			}
		}
	}
	return out
}
